name: Security Audit

on:
  push:
    branches: [main]
  pull_request:

jobs:
  pnpm-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - run: pnpm install --no-frozen-lockfile
      - run: pnpm audit --audit-level=high

